// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'This app is currently configured to run only on Android and iOS devices.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8eOGPju2Eodk7_eE2lnywP-2yP5vbYQ4',
    appId: '1:917276313680:android:5ff62662d8a9ba80a3a955',
    messagingSenderId: '917276313680',
    projectId: 'fitjourney-f4a76',
    storageBucket: 'fitjourney-f4a76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcYfdwx7ezgqKagYhvkvXqICKDlX3DA4w',
    appId: '1:917276313680:ios:3d195d2f913a21afa3a955',
    messagingSenderId: '917276313680',
    projectId: 'fitjourney-f4a76',
    storageBucket: 'fitjourney-f4a76.firebasestorage.app',
    iosBundleId: 'com.example.fitjourney',
  );
}
